### ISSUE TITLE
Support using a Cleaner instead of finalizers for Java 9+

### ISSUE THREAD

**Issue by bowbahdoe** [Dushistov/flapigen-rs#387] opened 2021-05-14 04:53 UTC
As of Java 9, finalizers have been depreciated.

https://stackoverflow.com/questions/52879761/should-java-9-cleaner-be-preferred-to-finalization

The general advice given is to have classes that maintain references to off-heap (from the perspective of the JVM) memory either

1. implement `AutoCloseable` and ask users to explicitly clean up the memory when they are done.
2. register the reference to what needs to be cleaned up with a `Cleaner` that will run some cleanup action when its container becomes PhantomReachable
3. build their own mechanism using PhantomReferences.
4. 1, but have 2 as a backup.

Of these options a Cleaner, while it incurs the cost of an extra OS thread, has the potential to make the nicest semantics for library users. There are likely a few issues to work out - like where that cleaner will be created and if the overhead is worth it to all uses - but it seems worth it to start that investigation.

**Comment by Dushistov** [comment] 2021-05-14 08:22
Close as duplicate of #303

**Closed by Dushistov** 2021-05-14 08:22 UTC
