### ISSUE TITLE
Java: How can I pass Option<T: ForeignClass> to and from Rust <-> Java

### ISSUE THREAD

**Issue by jawline** [Dushistov/flapigen-rs#375] opened 2021-01-28 06:16 UTC
I'm currently working on a project which needs to support both Android & iOS. When generating C++ bindings there are already foreign typemaps for Optional<ForeignClass> but for Java bindings there are not. Is there any way I can add this support to my bindings, or is there any way of specifying it on a per-class basis?

**Comment by Dushistov** [comment] 2021-01-29 15:44
It should work just fine with current master, see example: https://github.com/Dushistov/flapigen-rs/blob/master/jni_tests/src/test_optional.rs.in

**Comment by jawline** [comment] 2021-02-08 06:22
Oh so it is, thanks! Is there any conversion for the opposite case, I seem to be ok to return my foreign classes to Java-land but not to take an Option<ForeignClass> as an input for a method callback. The error I get is 
```
  error: Java code required to convert type to jobject
  It is impossible to use this Java code:
          {to_var_type};
          if ({from_var} != 0) {
              {to_var} = java.util.Optional.of(new Client(InternalPointerMarker.RAW_PTR, {from_var}));
          } else {
              {to_var} = java.util.Optional.empty();
          }

  for callback types conversation
    success = LoginHandler::success(&self, client: Option<ClientWrapper>);
                                                   ^^^^^^^^^^^^^^^^^^^^^
```
Where ClientWrapper is the Rust name and Client is the foreign class name.

**Comment by Dushistov** [comment] 2021-02-16 15:06
I close this issue as duplicate o #332 .

The problem is the same, for calling Java code from Rust we can not type conversation that uses Java code.

**Closed by Dushistov** 2021-02-16 15:06 UTC
Labels: Java/JNI
